### ISSUE TITLE
Missed notification sound

### ISSUE THREAD

**Issue by ghost** [quarck/StickyCalendar#1]
Hi, many compliment for your useful app!!!!
I've only one problem: notification sound (set into Google Calendar) doesn't play, I see only notification on Notification Bar.
If I uninstall your app I correctly hear notification sound set into setings of Google Calendar.
Any ideas?
Thanks a lot!!!

**Comment by quarck** [comment]
Hi Fenece,

Thanks for your feedback. Most likely I'm cancelling original notification
too early, so it has no chances to play a sound. I'll try adding some delay
in this, so allowing original notification to play sound and vibrate.
(Honestly - my phone is always on silent mode (e.g. vibration only), so
never noticed that sound might be missing).

Can't give you any particular timelines when it would get fixed - I'm doing
this project in my free time and I'm having way too little of it.

Regards,
Sergey

**Comment by ghost** [comment]
Thanks for your reply!!!
OK.... I think that the notification sound may be important for many people because (I speak for my experience) if I don't look the smartphone for a lot of time, without sound in a notification may I lose the appiontment.
So is possible for you to add a notification sound into your app for all notifications?
It's only an idea... thanks a lot for your time
Fenece

**Comment by quarck** [comment]
Hi Fenece, 

I did a new version that adds two options: 
- Delay notification replaced by 3 seconds, so original notification can play it's sound and vibrate and 3 seconds after it is replaced (this setting would be ON by default)
- Play it's own notification sound & vibrate (off by default) 

Please feel free to test it, I'll upload APK into Play Store after a bit of testing myself. Right now you can find new version here: https://dl.dropboxusercontent.com/u/25074445/StickyCalendar-1.1.6.apk (or get sources tagged as 'Release-1.1.6' and build it yourself if you prefer that way).

Thanks, 
Sergey

**Comment by quarck** [comment]
Seems working now, please re-open if it is still an issue.
